version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/SmartBank.API"
      - "/src/SmartBank.Core"
      - "/src/SmartBank.Infrastructure"
      - "/src/SmartBank.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
