-- SmartBank: baseline PostgreSQL schema (a FRESH database that equals the EF Core model, as of v1.3)
--
-- Use this to create the tables in an EMPTY PostgreSQL database: a local container (docker compose up -d db) or a new
-- Supabase project. It is NOT for an existing production database, which would fail on "table already exists".
-- Existing deployments are upgraded with the numbered scripts in this folder instead (v1.1, v1.2, v1.3, ...).
-- Do not run those upgrade scripts on a database created from this file: it already contains their changes.
--
-- Local example:
--   docker compose up -d db
--   docker compose exec -T db psql -U postgres -d smartbank < docs/deploy/00-baseline-postgres.sql
--
-- GENERATED FILE. It must be regenerated whenever the model changes (a new EF migration), otherwise a fresh database
-- drifts from the code. Regenerate with (the Host= makes the API pick the Npgsql provider; the two keys are throw-away):
--   dotnet tool restore
--   export JwtSettings__Key=any-string-of-at-least-32-characters-0000
--   export Encryption__Key=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
--   export ConnectionStrings__DefaultConnection="Host=localhost;Database=smartbank;Username=postgres;Password=x"
--   dotnet ef dbcontext script --project src/SmartBank.Infrastructure --startup-project src/SmartBank.API --output baseline.sql
-- then wrap the output in BEGIN; ... COMMIT; and put this header back on top (see the git history of this file).
-- The "MarketRates" table is part of the model but nothing reads or seeds it any more (rates come from the live feed).

BEGIN;

CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Action" character varying(50) NOT NULL,
    "Details" text NOT NULL,
    "IpAddress" character varying(64) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "MarketRates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(10) NOT NULL,
    "Buy" numeric(18,4) NOT NULL,
    "Sell" numeric(18,4) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MarketRates" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Version" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "Tckn" character varying(11) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "TwoFactorSecret" character varying(10),
    "TwoFactorExpiry" timestamp with time zone,
    "TwoFactorEnabled" boolean NOT NULL,
    "PendingOtpPurpose" integer,
    "PendingOtpBinding" character varying(64),
    "OtpFailedCount" integer NOT NULL,
    "FailedLoginCount" integer NOT NULL,
    "LockoutEnd" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "Accounts" (
    "Id" uuid NOT NULL,
    "Version" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "AccountNumber" character varying(20) NOT NULL,
    "AccountCode" character varying(15) NOT NULL,
    "Balance" numeric(18,2) NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EncryptedCardNumber" character varying(100) NOT NULL,
    "CardTheme" character varying(50) NOT NULL,
    "ExpiryDate" character varying(10) NOT NULL,
    "AccountType" character varying(30) NOT NULL,
    "InterestRate" numeric(5,2),
    "MaturityDate" timestamp with time zone,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ChatSessions" (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "Title" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "CreditCards" (
    "Id" uuid NOT NULL,
    "Version" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "EncryptedCardNumber" character varying(100) NOT NULL,
    "CardNumberHash" character varying(64),
    "ExpiryDate" character varying(10) NOT NULL,
    "CardLimit" numeric(18,2) NOT NULL,
    "CurrentDebt" numeric(18,2) NOT NULL,
    "CardTheme" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CreditCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CreditCards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(64) NOT NULL,
    "FamilyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    "CreatedByIp" character varying(64) NOT NULL,
    "Version" integer NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "SavedContacts" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AccountNumber" character varying(50) NOT NULL,
    "Alias" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SavedContacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavedContacts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Transactions" (
    "Id" uuid NOT NULL,
    "SourceAccountId" uuid,
    "DestinationAccountId" uuid,
    "Amount" numeric(18,2) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Type" text NOT NULL,
    "Category" character varying(50) NOT NULL DEFAULT 'Diğer',
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transactions_Accounts_DestinationAccountId" FOREIGN KEY ("DestinationAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Transactions_Accounts_SourceAccountId" FOREIGN KEY ("SourceAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ChatMessages" (
    "Id" uuid NOT NULL,
    "SessionId" uuid NOT NULL,
    "Sender" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_ChatSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ChatSessions" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CreditCardStatements" (
    "Id" uuid NOT NULL,
    "CreditCardId" uuid NOT NULL,
    "PeriodName" character varying(50) NOT NULL,
    "PeriodDebt" numeric(18,2) NOT NULL,
    "MinimumPayment" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "CutoffDate" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone NOT NULL,
    "IsPaid" boolean NOT NULL,
    CONSTRAINT "PK_CreditCardStatements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CreditCardStatements_CreditCards_CreditCardId" FOREIGN KEY ("CreditCardId") REFERENCES "CreditCards" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CreditCardTransactions" (
    "Id" uuid NOT NULL,
    "CreditCardId" uuid NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CreditCardTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CreditCardTransactions_CreditCards_CreditCardId" FOREIGN KEY ("CreditCardId") REFERENCES "CreditCards" ("Id") ON DELETE CASCADE
);


CREATE TABLE "StandingOrders" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "SourceAccountNumber" character varying(50) NOT NULL,
    "DestinationAccountNumber" character varying(50),
    "Amount" numeric(18,2),
    "Frequency" character varying(20) NOT NULL,
    "MaturityDate" timestamp with time zone NOT NULL,
    "NextExecutionDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "OrderType" character varying(20) NOT NULL,
    "CreditCardId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StandingOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StandingOrders_CreditCards_CreditCardId" FOREIGN KEY ("CreditCardId") REFERENCES "CreditCards" ("Id"),
    CONSTRAINT "FK_StandingOrders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);


CREATE UNIQUE INDEX "IX_Accounts_AccountCode" ON "Accounts" ("AccountCode");


CREATE UNIQUE INDEX "IX_Accounts_AccountNumber" ON "Accounts" ("AccountNumber");


CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");


CREATE INDEX "IX_AuditLogs_UserId_CreatedAt" ON "AuditLogs" ("UserId", "CreatedAt");


CREATE INDEX "IX_ChatMessages_SessionId_CreatedAt" ON "ChatMessages" ("SessionId", "CreatedAt");


CREATE INDEX "IX_ChatSessions_UserId" ON "ChatSessions" ("UserId");


CREATE UNIQUE INDEX "IX_CreditCards_CardNumberHash" ON "CreditCards" ("CardNumberHash");


CREATE UNIQUE INDEX "IX_CreditCards_UserId" ON "CreditCards" ("UserId");


CREATE INDEX "IX_CreditCardStatements_CreditCardId" ON "CreditCardStatements" ("CreditCardId");


CREATE INDEX "IX_CreditCardTransactions_CreditCardId" ON "CreditCardTransactions" ("CreditCardId");


CREATE INDEX "IX_RefreshTokens_FamilyId" ON "RefreshTokens" ("FamilyId");


CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE UNIQUE INDEX "IX_SavedContacts_UserId_AccountNumber" ON "SavedContacts" ("UserId", "AccountNumber");


CREATE INDEX "IX_StandingOrders_CreditCardId" ON "StandingOrders" ("CreditCardId");


CREATE INDEX "IX_StandingOrders_IsActive_NextExecutionDate" ON "StandingOrders" ("IsActive", "NextExecutionDate");


CREATE INDEX "IX_StandingOrders_UserId" ON "StandingOrders" ("UserId");


CREATE INDEX "IX_Transactions_DestinationAccountId_CreatedAt" ON "Transactions" ("DestinationAccountId", "CreatedAt");


CREATE INDEX "IX_Transactions_SourceAccountId_CreatedAt" ON "Transactions" ("SourceAccountId", "CreatedAt");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE UNIQUE INDEX "IX_Users_Tckn" ON "Users" ("Tckn");


CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

COMMIT;
